# Generated by Django 5.0.1 on 2024-02-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kysely', '0002_alter_kysymys_options_alter_vaihtoehto_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaihtoehto',
            old_name='äänet',
            new_name='ääniä',
        ),
    ]
